name: Setup RDP on Windows

on: [push, pull_request]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install xfreerdp
      run: choco install freerdp -y

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'

    - name: Set up RDP user
      run: |
        $username = "rdpuser"
        $password = "SecurePass123!"  # Use a shorter, strong password
        net user /add $username $password
        net localgroup "Remote Desktop Users" /add $username

    - name: Display RDP connection information
      run: |
        $ip = (Invoke-RestMethod -Uri 'http://ipinfo.io/json').ip
        Write-Host "Connect using the following credentials:"
        Write-Host "IP Address: $ip"
        Write-Host "Username: rdpuser"
        Write-Host "Password: SecurePass123!"
