name: Setup and Test RDP with Port Forwarding

on: [push, pull_request]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install RDP tools
      run: choco install freerdp -y

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
        
        # Restart Remote Desktop service
        Stop-Service -Name TermService -Force
        Start-Service -Name TermService

    - name: Add RDP user
      run: |
        $username = "rdpuser"
        $password = "SecurePass123"  # Ensure password meets complexity requirements
        $secPassword = ConvertTo-SecureString $password -AsPlainText -Force
        New-LocalUser -Name $username -Password $secPassword -FullName "RDP User" -Description "User for RDP"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username

    - name: Verify RDP setup
      run: |
        Get-Service -Name TermService

    - name: Install Node.js and localtunnel
      run: |
        choco install nodejs-lts -y
        npm install -g localtunnel

    - name: Start localtunnel
      id: localtunnel
      run: |
        lt --port 3389 --subdomain myrdp --local-hostname localhost > tunnel.log 2>&1 &
        Start-Sleep -Seconds 30  # Wait for localtunnel to initialize

    - name: Display Tunnel URL
      run: |
        $tunnelLog = Get-Content -Path 'tunnel.log' -Raw
        $tunnelUrl = ($tunnelLog | Select-String -Pattern 'your-rdp.localtunnel.me').Line
        Write-Host "LocalTunnel URL: $tunnelUrl"
        Write-Host "Username: rdpuser"
        Write-Host "Password: SecurePass123"

    - name: Test RDP connection
      run: |
        Write-Host "Test the RDP connection using the LocalTunnel URL obtained above."
