name: Setup RDP on Windows

on: [push, pull_request]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install xfreerdp
      run: choco install freerdp -y

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
        
        # Stop TermService with Force
        Stop-Service -Name TermService -Force

        # Start TermService
        Start-Service -Name TermService

    - name: Set up RDP user
      run: |
        $username = "rdpuser"
        $password = "SecurePass123"  # Shortened password to meet the requirement
        net user /add $username $password /Y
        net localgroup "Remote Desktop Users" $username /add

    - name: Verify RDP service status
      run: |
        Get-Service -Name TermService

    - name: Display RDP connection information
      run: |
        $ip = (Invoke-RestMethod -Uri 'http://ipinfo.io/json').ip
        Write-Host "Connect using the following credentials:"
        Write-Host "IP Address: $ip"
        Write-Host "Username: rdpuser"
        Write-Host "Password: SecurePass123"

    - name: Test RDP connection
      run: |
        $ip = (Invoke-RestMethod -Uri 'http://ipinfo.io/json').ip
        $command = "xfreerdp /u:rdpuser /p:SecurePass123 /v:$ip"
        Write-Host "Running command: $command"
        Start-Process -NoNewWindow -FilePath "xfreerdp.exe" -ArgumentList "/u:rdpuser /p:SecurePass123 /v:$ip"
