name: Setup and Test RDP with Port Forwarding

on: [push, pull_request]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install RDP tools
      run: choco install freerdp -y

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
        
        # Restart Remote Desktop service
        Stop-Service -Name TermService -Force
        Start-Service -Name TermService

    - name: Add RDP user
      run: |
        $username = "rdpuser"
        $password = "SecurePass123"  # Ensure password meets complexity requirements
        $secPassword = ConvertTo-SecureString $password -AsPlainText -Force
        New-LocalUser -Name $username -Password $secPassword -FullName "RDP User" -Description "User for RDP"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username

    - name: Verify RDP setup
      run: |
        Get-Service -Name TermService

    - name: Install SSH client
      run: choco install openssh -y

    - name: Ensure .ssh directory exists
      run: |
        if (!(Test-Path "$env:USERPROFILE\.ssh")) {
          New-Item -Path "$env:USERPROFILE\.ssh" -ItemType Directory
        }

    - name: Create SSH key pair if it doesn't exist
      run: |
        if (!(Test-Path "$env:USERPROFILE\.ssh\id_rsa")) {
          ssh-keygen -t rsa -b 4096 -f "$env:USERPROFILE\.ssh\id_rsa" -N ""
        }

    - name: Set up Serveo tunnel
      run: |
        $sshCommand = "ssh -o StrictHostKeyChecking=no -T -R 3389:localhost:3389 serveo.net"
        Start-Process -NoNewWindow -FilePath "cmd.exe" -ArgumentList "/c $sshCommand" -PassThru | Wait-Process

    - name: Wait for Serveo to initialize
      run: |
        Start-Sleep -Seconds 60  # Increase wait time if needed

    - name: Get Serveo public URL
      id: serveo
      run: |
        Write-Host "Please manually check Serveo for the public URL. Serveo does not provide a direct API for URL retrieval."

    - name: Display RDP connection information
      run: |
        Write-Host "Connect using the Serveo URL obtained manually."
        Write-Host "Username: rdpuser"
        Write-Host "Password: SecurePass123"

    - name: Test RDP connection
      run: |
        Write-Host "Test the RDP connection using the Serveo URL obtained manually."
