name: Setup and Test RDP with Port Forwarding

on: [push, pull_request]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install RDP tools
      run: choco install freerdp -y

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
        
        # Restart Remote Desktop service
        Stop-Service -Name TermService -Force
        Start-Service -Name TermService

    - name: Add RDP user
      run: |
        $username = "rdpuser"
        $password = "SecurePass123"  # Ensure password meets complexity requirements
        $secPassword = ConvertTo-SecureString $password -AsPlainText -Force
        New-LocalUser -Name $username -Password $secPassword -FullName "RDP User" -Description "User for RDP"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username

    - name: Verify RDP setup
      run: |
        Get-Service -Name TermService

    - name: Install Node.js and localtunnel
      run: |
        choco install nodejs-lts -y
        npm install -g localtunnel

    - name: Start localtunnel
      run: |
        lt --port 3389 --subdomain your-custom-subdomain --local-hostname localhost &
        Start-Sleep -Seconds 30  # Wait for localtunnel to initialize

    - name: Display RDP connection information
      run: |
        Write-Host "Connect using the localtunnel URL obtained from the 'lt' command."
        Write-Host "Username: rdpuser"
        Write-Host "Password: SecurePass123"
