name: Setup RDP and LocalXpose on Windows VM

on: [push]

jobs:
  setup:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install LocalXpose using Chocolatey
      run: choco install localxpose -y

    - name: Enable RDP
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
        # Enable RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
        
    - name: Set RDP Password
      run: |
        $username = "siddhant"
        $password = "kali"
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ($username, $securePassword)
        net user $username $password

    - name: Configure LocalXpose for Port Forwarding
      run: |
        localxpose tcp --local-port 3389 --remote-port 3389 --auth ${{ secrets.LOCALXPOSE_API_KEY }}

    - name: Output RDP and LocalXpose Details
      run: |
        Write-Output "RDP is now enabled on the Windows VM. Use the following credentials:"
        Write-Output "Username: your-username"
        Write-Output "Password: your-password"
        Write-Output "LocalXpose is configured to forward port 3389. Use the following details:"
        Write-Output "API Key: ${{ secrets.LOCALXPOSE_API_KEY }}"
