name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://github.com/avgvstvs/miscellaneous/raw/main/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://github.com/avgvstvs/miscellaneous/raw/main/nssm.exe -OutFile nssm.exe
    
    - name: Copy NSSM & Ngrok to Windows Directory
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    
    - name: Enable RDP Network Level Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    
    - name: Firewall Allow RDP
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    
    - name: Create Tunnel
      run: sc start ngrok
    
    - name: Connect to RDP [User:sid Password:kali]
      run: cmd /c start ngrok.exe tcp 3389
    
    - name: Keep Alive
      run: ./loop.ps1
