name: Setup and Test RDP on Windows

on: [push, pull_request]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install RDP tools
      run: |
        # Ensure that PowerShell is run as Administrator
        Start-Process powershell -ArgumentList 'choco install freerdp -y' -Verb runAs

    - name: Enable Remote Desktop
      run: |
        # Enable Remote Desktop through PowerShell
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
        
        # Restart Remote Desktop service
        Stop-Service -Name TermService -Force
        Start-Service -Name TermService

    - name: Add RDP user
      run: |
        $username = "rdpuser"
        $password = "SecurePass123"  # Ensure password meets complexity requirements
        $secPassword = ConvertTo-SecureString $password -AsPlainText -Force
        New-LocalUser -Name $username -Password $secPassword -FullName "RDP User" -Description "User for RDP"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username

    - name: Verify RDP setup
      run: |
        Get-Service -Name TermService

    - name: Display connection details
      run: |
        $ip = (Invoke-RestMethod -Uri 'http://ipinfo.io/json').ip
        Write-Host "Connect using the following credentials:"
        Write-Host "IP Address: $ip"
        Write-Host "Username: rdpuser"
        Write-Host "Password: SecurePass123"

    - name: Test RDP connection
      run: |
        # Open an RDP connection (simplified, usually requires a GUI)
        $ip = (Invoke-RestMethod -Uri 'http://ipinfo.io/json').ip
        $rdpCommand = "mstsc /v:$ip"
        Write-Host "Running command: $rdpCommand"
        Start-Process -NoNewWindow -FilePath "mstsc.exe" -ArgumentList "/v:$ip"
