name: Setup and Test RDP with Port Forwarding

on: [push, pull_request]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install ngrok using Chocolatey
      run: choco install ngrok -y

    - name: Install RDP tools
      run: choco install freerdp -y

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
        
        # Restart Remote Desktop service
        Stop-Service -Name TermService -Force
        Start-Service -Name TermService

    - name: Add RDP user
      run: |
        $username = "rdpuser"
        $password = "SecurePass123"  # Ensure password meets complexity requirements
        $secPassword = ConvertTo-SecureString $password -AsPlainText -Force
        New-LocalUser -Name $username -Password $secPassword -FullName "RDP User" -Description "User for RDP"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username

    - name: Verify RDP setup
      run: |
        Get-Service -Name TermService

    - name: Configure ngrok with auth token
      run: |
        $ngrokToken = $env:NGROK_AUTH_TOKEN
        ngrok authtoken $ngrokToken

    - name: Start ngrok for port forwarding
      run: |
        Start-Process -NoNewWindow -FilePath "ngrok.exe" -ArgumentList "tcp 3389" -PassThru | Wait-Process

    - name: Wait for ngrok to initialize
      run: |
        Start-Sleep -Seconds 20  # Increase wait time

    - name: Get ngrok public URL
      id: ngrok
      run: |
        $ngrokInfo = Invoke-RestMethod -Uri http://localhost:4040/api/tunnels
        if ($ngrokInfo -eq $null -or $ngrokInfo.tunnels.Count -eq 0) {
          Write-Error "Failed to retrieve ngrok tunnel information"
          exit 1
        }
        $publicUrl = $ngrokInfo.tunnels[0].public_url
        Write-Output "ngrok_url=$publicUrl" >> $env:GITHUB_ENV

    - name: Display RDP connection information
      run: |
        $publicUrl = $env:ngrok_url
        Write-Host "Connect using the following credentials:"
        Write-Host "Public URL: $publicUrl"
        Write-Host "Username: rdpuser"
        Write-Host "Password: SecurePass123"

    - name: Test RDP connection
      run: |
        $publicUrl = $env:ngrok_url
        Write-Host "Testing RDP connection to $publicUrl"
        Start-Process -NoNewWindow -FilePath "mstsc.exe" -ArgumentList "/v:$publicUrl"
