name: Setup RDP and Localtonet on Windows VM

on: [push]

jobs:
  setup:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install wget
      run: choco install wget -y

    - name: Download Localtonet
      run: wget https://localtonet.com/download/localtonet-win-64.zip -O localtonet.zip

    - name: Unzip Localtonet
      run: powershell -Command "Expand-Archive -Path localtonet.zip -DestinationPath ."

    - name: Make Localtonet Executable
      run: chmod +x ./localtonet

    - name: Enable RDP
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
        # Enable RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
        
    - name: Ensure RDP User Exists
      run: |
        $username = "your-username"
        $password = "P@ssw0rd!2024"  # Use a complex password
        # Check if the user exists
        $user = Get-LocalUser -Name $username -ErrorAction SilentlyContinue
        if (-not $user) {
          # Create the user if it doesn't exist
          New-LocalUser -Name $username -Password (ConvertTo-SecureString $password -AsPlainText -Force) -FullName "RDP User" -Description "User for RDP access"
          Add-LocalGroupMember -Group "Administrators" -Member $username
        }
        else {
          # Update the password if the user already exists
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
          Set-LocalUser -Name $username -Password $securePassword
        }

    - name: Configure Localtonet for Port Forwarding
      env:
        AUTHTOKEN: ${{ secrets.LOCALTONET_AUTH_TOKEN }}
      run: ./localtonet authtoken $AUTHTOKEN && ./localtonet tcp 3389
