name: Setup and Test RDP with Port Forwarding

on: [push, pull_request]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install RDP tools
      run: choco install freerdp -y

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
        
        # Restart Remote Desktop service
        Stop-Service -Name TermService -Force
        Start-Service -Name TermService

    - name: Add RDP user
      run: |
        $username = "rdpuser"
        $password = "SecurePass123"  # Ensure password meets complexity requirements
        $secPassword = ConvertTo-SecureString $password -AsPlainText -Force
        New-LocalUser -Name $username -Password $secPassword -FullName "RDP User" -Description "User for RDP"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username

    - name: Verify RDP setup
      run: |
        Get-Service -Name TermService

    - name: Set up Serveo tunnel
      run: |
        # Install OpenSSH if not already installed
        choco install openssh -y
        Start-Service ssh-agent
        Set-Service -Name ssh-agent -StartupType Automatic

        # Create SSH key pair if it doesn't exist
        if (!(Test-Path "$env:USERPROFILE\.ssh\id_rsa")) {
          ssh-keygen -t rsa -b 4096 -f "$env:USERPROFILE\.ssh\id_rsa" -N ""
        }

        # Connect to Serveo to create a tunnel
        Start-Process -NoNewWindow -FilePath "ssh.exe" -ArgumentList "-R 3389:localhost:3389 serveo.net" -PassThru | Wait-Process

    - name: Wait for Serveo to initialize
      run: |
        Start-Sleep -Seconds 20  # Increase wait time

    - name: Get Serveo public URL
      id: serveo
      run: |
        # Serveo does not provide a REST API like ngrok, so this step is manual
        Write-Output "Please manually check Serveo for the public URL"

    - name: Display RDP connection information
      run: |
        Write-Host "Connect using the Serveo URL obtained manually."
        Write-Host "Username: rdpuser"
        Write-Host "Password: SecurePass123"

    - name: Test RDP connection
      run: |
        # Display a message to manually test the connection
        Write-Host "Test the RDP connection using the Serveo URL."
