name: Setup and Test RDP with Port Forwarding

on: [push, pull_request]

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install RDP tools
      run: choco install freerdp -y

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'
        
        # Restart Remote Desktop service
        Stop-Service -Name TermService -Force
        Start-Service -Name TermService

    - name: Add RDP user
      run: |
        $username = "rdpuser"
        $password = "SecurePass123"  # Ensure password meets complexity requirements
        $secPassword = ConvertTo-SecureString $password -AsPlainText -Force
        New-LocalUser -Name $username -Password $secPassword -FullName "RDP User" -Description "User for RDP"
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username

    - name: Verify RDP setup
      run: |
        Get-Service -Name TermService

    - name: Install OpenVPN
      run: choco install openvpn -y

    - name: Configure OpenVPN
      run: |
        # Create OpenVPN configuration directory if it doesn't exist
        if (!(Test-Path "C:\Program Files\OpenVPN\config")) {
          New-Item -Path "C:\Program Files\OpenVPN\config" -ItemType Directory
        }

        # Copy the OpenVPN configuration file
        Copy-Item -Path "magnetissimo.first.ovpn" -Destination "C:\Program Files\OpenVPN\config\magnetissimo.first.ovpn"

    - name: Start OpenVPN
      run: |
        Start-Service -Name openvpnservice
        Start-Sleep -Seconds 30  # Wait for VPN to establish connection

    - name: Start RDP Tunnel
      run: |
        Start-Process -NoNewWindow -FilePath "cmd.exe" -ArgumentList "/c start /B C:\Program Files\OpenVPN\bin\openvpn.exe --config C:\Program Files\OpenVPN\config\magnetissimo.first.ovpn"
        Start-Sleep -Seconds 30  # Wait for tunnel to establish

    - name: Display RDP connection information
      run: |
        Write-Host "RDP service is now accessible via the OpenVPN tunnel."
        Write-Host "Username: rdpuser"
        Write-Host "Password: SecurePass123"
